name: demo.playwright.pwc
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  basicTests:
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the job in parallel
        shard: [1, 2, 3]

    name: "Playwright Tests - pwc"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:1.46.1

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # https://github.com/actions/runner-images/issues/6775
      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chrome

      - name: Run Project A
        continue-on-error: false
        working-directory: ./basic
        env:
          CURRENTS_PROJECT_ID: bnsqNa
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          npx pwc --project a --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Run Project B
        continue-on-error: false
        working-directory: ./basic
        env:
          CURRENTS_PROJECT_ID: bnsqNa
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          npx pwc --project  --shard=${{ matrix.shard }}/${{ strategy.job-total }}
